vim.keymap.set({ 'n', 'i' }, '<M-J>', '<Cmd>copy .<cr>', { desc = 'Copy Line Down' })
vim.keymap.set({ 'n', 'i' }, '<M-K>', '<Cmd>copy .-1<cr>', { desc = 'Copy Line Up' })
vim.keymap.set('x', '<M-J>', ":<C-u>'<,'>copy '<-1<cr>gv=gv", { desc = 'Copy Selection Down' })
vim.keymap.set('x', '<M-K>', ":<C-u>'<,'>copy '><cr>gv=gv", { desc = 'Copy Selection Up' })

vim.keymap.set('n', '<C-s>', '<Cmd>w<CR>', { desc = 'Force write', silent = true })

vim.keymap.set({ 'i', 'c' }, '<C-v>', '<C-r>+', { desc = 'Paste' })

vim.keymap.set('n', '<Esc>', '<Cmd>nohlsearch<CR>', { desc = 'Clear search highlight' })

vim.keymap.set('n', '<C-Left>', '"<Cmd>vertical resize -" . v:count1 . "<CR>"', { expr = true, replace_keycodes = false, desc = 'Decrease window width' })
vim.keymap.set('n', '<C-Down>', '"<Cmd>resize -" . v:count1 . "<CR>"', { expr = true, replace_keycodes = false, desc = 'Decrease window height' })
vim.keymap.set('n', '<C-Up>', '"<Cmd>resize +" . v:count1 . "<CR>"', { expr = true, replace_keycodes = false, desc = 'Increase window height' })
vim.keymap.set('n', '<C-Right>', '"<Cmd>vertical resize +" . v:count1 . "<CR>"', { expr = true, replace_keycodes = false, desc = 'Increase window width' })

vim.keymap.set('n', 'K', function() vim.lsp.buf.hover({ max_width = 100, max_height = 20, border = 'solid' }) end, { desc = 'vim.lsp.buf.hover()' })
vim.keymap.set('n', '<leader>ld', function() vim.diagnostic.open_float(nil, { focusable = true, border = 'solid' }) end, { desc = 'Hover diagnostic' })
vim.keymap.set({ 'n', 'x' }, 'g.', vim.lsp.buf.code_action, { desc = 'Code Action' })
vim.keymap.set('n', 'gai', function() Snacks.picker.lsp_incoming_calls() end, { desc = 'Calls Incoming' })
vim.keymap.set('n', 'gao', function() Snacks.picker.lsp_outgoing_calls() end, { desc = 'Calls Outgoing' })
vim.keymap.set('n', 'gd', function() Snacks.picker.lsp_definitions() end, { desc = 'Goto Definition' })
vim.keymap.set('n', 'gD', function() Snacks.picker.lsp_declarations() end, { desc = 'Goto Declaration' })
vim.keymap.set('n', 'gO', function() Snacks.picker.lsp_symbols() end, { desc = 'LSP document symbols' })
vim.keymap.set('n', 'gri', function() Snacks.picker.lsp_implementations() end, { desc = 'Goto Implementation' })
vim.keymap.set('n', 'grr', function() Snacks.picker.lsp_references() end, { desc = 'References' })
vim.keymap.set('n', 'gy', function() Snacks.picker.lsp_type_definitions() end, { desc = 'Goto Type Definition' })
vim.keymap.set('n', '<leader>lf', vim.lsp.buf.format, { desc = 'Format buffer' })

vim.keymap.set('n', '<C-w>gd', function()
  vim.cmd.vsplit()
  Snacks.picker.lsp_definitions()
end, { desc = 'Go to definition in a new vertical split' })
vim.keymap.set('n', '<C-w>gD', function()
  vim.cmd.vsplit()
  Snacks.picker.lsp_declarations()
end, { desc = 'Go to declaration in a new vertical split' })
vim.keymap.set('n', '<C-w>gy', function()
  vim.cmd.vsplit()
  Snacks.picker.lsp_type_definitions()
end, { desc = 'Go to type_definition in a new vertical split' })

local ts_repeat_move = require('nvim-treesitter.textobjects.repeatable_move')
vim.keymap.set({ 'n', 'x', 'o' }, ';', ts_repeat_move.repeat_last_move)
vim.keymap.set({ 'n', 'x', 'o' }, ',', ts_repeat_move.repeat_last_move_opposite)
vim.keymap.set({ 'n', 'x', 'o' }, 'f', ts_repeat_move.builtin_f_expr, { expr = true })
vim.keymap.set({ 'n', 'x', 'o' }, 'F', ts_repeat_move.builtin_F_expr, { expr = true })
vim.keymap.set({ 'n', 'x', 'o' }, 't', ts_repeat_move.builtin_t_expr, { expr = true })
vim.keymap.set({ 'n', 'x', 'o' }, 'T', ts_repeat_move.builtin_T_expr, { expr = true })

vim.keymap.set('n', '<leader>e', function() if not MiniFiles.close() then MiniFiles.open() end end, { desc = 'Toggle Explorer' })

-- Disable `s` shortcut (use `cl` instead) for safer usage of 'mini.surround'
vim.keymap.set({ 'n', 'x' }, 's', '<Nop>')

vim.keymap.set('n', "<leader>f'", function() Snacks.picker.marks() end, { desc = 'Find marks' })
vim.keymap.set('n', '<leader>f/', function() Snacks.picker.search_history() end, { desc = 'Find search history' })
vim.keymap.set('n', '<leader>f:', function() Snacks.picker.command_history() end, { desc = 'Find command history' })
vim.keymap.set('n', '<leader>fb', function() Snacks.picker.buffers() end, { desc = 'Find buffers' })
vim.keymap.set('n', '<leader>fe', function() Snacks.picker.explorer() end, { desc = 'File explorer' })
vim.keymap.set('n', '<leader>ff', function() Snacks.picker.files({ hidden = true }) end, { desc = 'Find files' })
vim.keymap.set('n', '<leader>fF', function() Snacks.picker.files({ hidden = true, ignored = true }) end, { desc = 'Find all files' })
vim.keymap.set('n', '<leader>fh', function() Snacks.picker.help() end, { desc = 'Find help' })
vim.keymap.set('n', '<leader>fH', function() Snacks.picker.highlights() end, { desc = 'Find highlights' })
vim.keymap.set('n', '<leader>fi', function() Snacks.picker.icons() end, { desc = 'Find icons' })
vim.keymap.set('n', '<leader>fk', function() Snacks.picker.keymaps() end, { desc = 'Find keymaps' })
vim.keymap.set('n', '<leader>fr', function() Snacks.picker.registers() end, { desc = 'Find registers' })
vim.keymap.set('n', '<leader>ft', function() Snacks.picker.colorschemes() end, { desc = 'Find themes' })
vim.keymap.set('n', '<leader>fu', function() Snacks.picker.undo() end, { desc = 'Find undo history' })
vim.keymap.set('n', '<leader>fw', function() Snacks.picker.grep() end, { desc = 'Find words' })
vim.keymap.set('n', '<leader>fW', function() Snacks.picker.grep({ hidden = true, ignored = true }) end, { desc = 'Find all words' })
vim.keymap.set('n', '<leader>lD', function() Snacks.picker.diagnostics() end, { desc = 'Search diagnostic' })
vim.keymap.set('n', '<leader>lG', function() Snacks.picker.lsp_workspace_symbols() end, { desc = 'LSP Workspace Symbols' })

vim.keymap.set('n', '<leader>nh', function() MiniNotify.show_history() end, { desc = 'Notify history' })

vim.keymap.set({ 'n', 'x' }, 'gX', function() Snacks.gitbrowse() end, { desc = 'Git browse (open)' })
